version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pix-gateways-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pix-gateways-network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_DATABASE=pix_gateways
      - DB_USERNAME=pix_gateways
      - DB_PASSWORD=root
      - REDIS_HOST=redis

  webserver:
    image: nginx:alpine
    container_name: pix-gateways-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pix-gateways-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: pix-gateways-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pix_gateways
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: pix_gateways
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pix-gateways-network

  redis:
    image: redis:alpine
    container_name: pix-gateways-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pix-gateways-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pix-gateways-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --verbose --tries=3 --timeout=90
    networks:
      - pix-gateways-network
    depends_on:
      - app
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_DATABASE=pix_gateways
      - DB_USERNAME=pix_gateways
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis

networks:
  pix-gateways-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

